### ISSUE TITLE
Emulatrix in IFRAME - freezes on Blink (Chrome / Edge / Opera), not on Firefox (Gecko)

### ISSUE THREAD

**Issue by perelowski** [lrusso/Emulatrix#15]
Hello,

I recently tried to run the Emulatrix in an iframe on my blog. After uploading a ROM, the game ran smoothly, but when I clicked outside of the iframe, the game paused and couldn't be restored. It happens only in Blink engine based browsers (Chrome / Edge / Opera), Firefox is not affected. Can you check it? Example URL on which I tested is here: https://zmozgu.net/donkey-kong-na-snesa/

**Comment by lrusso** [comment]
Hi, Emulatrix doesn't work properly within an iframe because the emulation core never regain focus from the browser. I just patched the index.html in order to prevent iframes to be used over it.

Best regards and thanks for the report,
Leonardo

**Comment by perelowski** [comment]
Thanks for a quick reply. Can you tell me how does it refer to the issue #7 (https://github.com/lrusso/Emulatrix/issues/7) where you explicitly recommend using Emulatrix in an iframe?

**Comment by lrusso** [comment]
Because that was an old release of Emulatrix. Initially the libretro compilation didn't handle the window state. So you can switch between tabs and the game will be paused, but if you switch between windows, the game wasn't paused. Because of that, I modified the code of every libretro core in order to handle the window event as well. I also applied the same logic to the DOSBox core.
