### ISSUE TITLE
Safari version isn't working.

### ISSUE THREAD

**Issue by azoreseuropa** [lrusso/Emulatrix#18]
I am not noob and I have been used many emulators for many many years. I am curious about this one. The problem is: 

<img width="334" alt="Screen Shot 2020-10-18 at 9 47 15 AM" src="https://user-images.githubusercontent.com/16481778/96363935-01693180-1127-11eb-9e93-8f6166d1f6aa.png">

Can you make it work with Safari for macOS users ? It will be great for people who do not know about emulators.

**Comment by lrusso** [comment]
Hi, the different libretro cores crashes in Safari for different reasons in each case. The DOSBox porting can be executed in Safari but crashes after a few seconds. I patched the code of each core and porting in order to handle the window resizing, saving/load states/files and a also fix a few bugs in DOSBox. But, just as an example, the AudioContext works differently in Safari and that only it would require a rework of the audio logic, maybe in a future with further development.
