### ISSUE TITLE
How to disable the bilinear filter?

### ISSUE THREAD

**Issue by JosekeyRandom** [lrusso/Emulatrix#30]
Hi, I love the project you have done, it is spectacular.

Is there any way to disable the bilinear filter?
Why do emulators go wrong in firefox? In chrome, brave, edge they are much better.

Thanks for the job.

**Comment by lrusso** [comment]
Hello, thank your for your message and kind words.

The bilinear filter is the default mode that the Retroarch Emscripten porting has. I haven't tried to remove it because at least for me it looks fine. You can read about the Retroarch configuration at https://github.com/libretro/RetroArch/blob/master/retroarch.cfg.

For last, I'm guessing that it depends of the Browser engine and CPU, in my laptop with OS X, Emulatrix runs smooth on Firefox and Chrome as well.

Best regards,
Leonardo

**Comment by JosekeyRandom** [comment]
Ok thank you very much the truth is that it looks better with the bilinear filter but it was in case there was a possibility of disabling it, thank you very much for the prompt response.
