### ISSUE TITLE
mute and save game

### ISSUE THREAD

**Issue by pavelbv2** [lrusso/Emulatrix#4]
Hello.

Is it possible to somehow enable these settings now?
```
// SETS THE KEYS FOR UNWANTED FUNCTIONS
				config += "input_audio_mute = " + emptyValue + "\n";
				config += "input_pause_toggle = " + emptyValue + "\n";
				config += "input_save_state = " + emptyValue + "\n";
				config += "input_load_state = " + emptyValue + "\n";

```
I really need a mute.

Thank.

**Comment by lrusso** [comment]
Hello,

Regarding the mute key, is not necessary because you can mute the browser tab:

https://www.howtogeek.com/231959/how-to-mute-individual-browser-tabs-in-chrome-safari-and-firefox/

On the other hand, regarding the save_state and load_state keys, the emscripten porting of the libretro emulator doesn't have a compatible feature for that yet.

Best regards,
Leonardo
