### ISSUE TITLE
How to embed this in my own website?

### ISSUE THREAD

**Issue by TwilightSparkleLover** [lrusso/Emulatrix#7]
I want to showcase a multicart that I've find everywhere, and finally found (read: Mario & Battle City)

**Comment by lrusso** [comment]
Hello, you can embed Emulatrix in your website by using a iframe.

<iframe src="https://lrusso.github.io/Emulatrix/Emulatrix.htm"></iframe> 

https://www.w3schools.com/tags/tag_iframe.asp

**Comment by TwilightSparkleLover** [comment]
> Hello, you can embed Emulatrix in your website by using a iframe.
> 
> <iframe src="https://lrusso.github.io/Emulatrix/Emulatrix.htm"></iframe>
> https://www.w3schools.com/tags/tag_iframe.asp

Not that meaning.
I mean, making the game auto start in the iframe.

**Comment by TwilightSparkleLover** [comment]
Also I can't load the emulator offline by clicking the main html

**Comment by lrusso** [comment]
Emulatrix requires a web server to work, it won't work if you download the files and browse the offline files in your computer. For last, I guess that you could use a code for auto start (read https://github.com/lrusso/Emulatrix/issues/3 for some additional info), but you won't have audio. Chromium requires a user interaction to allow the AudioContext to work, so if the auto start is executed, you won't have audio because of it. The user must click on some element and that element must trigger the loading process.
